-- Migration: V20250427_190448__alteracoes_cad_atividades.sql

-- Escreva seu SQL aqui...
drop table cad_ativ_dias_semana;

create table cad_atividades_mes_ano(
id SERIAL,
id_atividade integer,
mes integer,
ano integer,
constraint pk_cad_atividades_mes_ano PRIMARY KEY (ID),
CONSTRAINT FK_CAD_ATIVIDADES_MES_ANO_ATIV FOREIGN KEY (ID_ATIVIDADE) REFERENCES CAD_ATIVIDADES(ID)
);
CREATE INDEX IDX_CAD_ATIVIDADES_MES_ANO_ID ON CAD_ATIVIDADES_MES_ANO (ID);
CREATE INDEX IDX_CAD_ATIVIDADES_MES_ANO_ID_ATIVIDADE ON CAD_ATIVIDADES_MES_ANO(ID_ATIVIDADE);

CREATE TABLE CAD_ATIVIDADES_DIAS_MES(
ID SERIAL,
ID_MES_ANO INTEGER,
ID_ATIVIDADE INTEGER,
DIA_MES INTEGER,
CONSTRAINT PK_CAD_ATIVIDADES_DIAS_MES PRIMARY KEY(ID),
CONSTRAINT FK_CAD_ATIVIDADES_DIAS_MES_ANO FOREIGN KEY (ID_MES_ANO) REFERENCES CAD_ATIVIDADES_MES_ANO(ID),
CONSTRAINT FK_CAD_ATIVIDADES_DIAS_ATIVIDADE FOREIGN KEY(ID_ATIVIDADE) REFERENCES CAD_ATIVIDADES(ID)
);

CREATE INDEX idx_id_mes_ano ON CAD_ATIVIDADES_DIAS_MES(ID_MES_ANO);
CREATE INDEX idx_id_atividade ON CAD_ATIVIDADES_DIAS_MES(ID_ATIVIDADE);