-- Migration: V20250427_220652__alteracoes_cad_atividades.sql

-- Escreva seu SQL aqui...

alter table cad_atividades_grupos
DROP COLUMN COD_ATIVIDADE;

ALTER TABLE CAD_ATIV_GRUPOS_ALUNOS
ADD COD_GRUPO INTEGER,
add CONSTRAINT FK_CAD_ATIV_GRUPOS_ALUNOS_GRUPOS FOREIGN KEY (COD_GRUPO) REFERENCES CAD_ATIVIDADES_GRUPOS (ID);